### ISSUE TITLE
Dモジュールドキュメント改善点

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/perlzemitut#6]
Dモジュールドキュメントのレビューです。

本体の英語も含めたレビューです。英語本体のドキュメントを変更した上で、日本語にも変更を加えます。

<b>インストール</b>

削除します。

<b>利用例</b>

・dustr, dnstr, dwstrは、ユーザーからみて補助的な機能なので、利用例には加えない
・「use D;du $date」「use D;dw $date」「use D;dn $date」のワンライナーの利用例を加える
・du関数の出力結果のサンプルを末尾に加える(二つ目のサンプルとして)

<b>関数</b>

説明を入れ替えます。dustrメインの説明になっているのを、ユーザーから見てメインで利用する、du関数メインの説明に変えます。

```
dustr関数

リファレンスデータ内のすべての文字列をUTF-8にエンコードし、リファレンスデータをファイル名, 行番号とともに文字列を返却します。

引数が文字列などの参照データでない場合も、リファレンスデータと同じ方法でダンプされます。

du関数

dustr関数の結果を標準エラー出力へダンプします。
```

また、それぞれの関数の場所で、コードのサンプルを加えます。ワンライナーについても、説明。

順番変更。du,dw,dnが先、その後ろにdustr, dwstr, dnstr。

<b>エクスポートされる関数</b>

この項目を削除して、関数のそれぞれの解説に「この関数は、エクスポートされます」と追加してください。

**Comment by YoshiyukiItoh** [comment]
ドキュメント更新を始めました。
markdownをリアルタイムでなくても良いので確認しながら編集したいと考えましたが、
そのようなツールなどはありますでしょうか？
b843a8c98c81956280dcb1b4f5090e537a92d5b0

（関数ごとにコードサンプルを入れましたら完了の予定です）

**Comment by yuki-kimoto** [comment]
ありがとうございます。微修正して、アップします。

**Comment by yuki-kimoto** [comment]
https://metacpan.org/pod2html

**Comment by YoshiyukiItoh** [comment]
現時点でずれなどなさそうだと確認できました。
他にイメージと違った箇所など私の方で直せる箇所あれば教えてください。

**Comment by YoshiyukiItoh** [comment]
ご確認お願いいたします。
https://github.com/yuki-kimoto/perlzemitut/pull/8
