### ISSUE TITLE
「OS名を取得する $^O」ページ

### ISSUE THREAD

**Issue by tani-ro-hei** [yuki-kimoto/perlzemitut#7]
https://tutorial.perlzemi.com/blog/20180527152759.html
「Windows 全般」のところに余計な | が入っていて、表示がおかしいです。

**Comment by yuki-kimoto** [comment]
ご報告、ありがとうございます。余計な「|」を消します!

**Comment by yuki-kimoto** [comment]
初めましてでしょうか?

お会いしていたらすみません。

**Comment by tani-ro-hei** [comment]
あどうも、たまたま目に留まったので、つい名乗らず。少し前に PerlZemi の Slack に入れて頂きましたが、あまり発言できておらずすみません。ネット上でたまにすれ違いますが、お会いしたことはないはずです。

**Comment by yuki-kimoto** [comment]
PerlゼミのSlackに登録してくださった方なのですね。

ご指摘、ありがとうございます!

**Comment by yuki-kimoto** [comment]
修正しました。
